

python sweep_all_test_settable_size5.py --output-type perf --run-name tx-size-bf-extern-with_1 --cfg-filepath ./configs/tx_size_comparison.json  --dto-version extern --num-iter 10000000 --exclude-pfs --num-dsas 1 --results-dirname  tx_size_bf_extern_with_stats
python sweep_all_test_settable_size5.py --output-type micro --run-name tx-size-bf-extern-nodto_1 --cfg-filepath ./configs/tx_size_comparison.json  --dto-version no --no-stats --num-iter 10000000 --exclude-pfs --num-dsas 1 --results-dirname  tx_size_bf_extern_no_dto
python sweep_all_test_settable_size5.py --output-type micro --run-name tx-size-bf-extern-nostats_1 --cfg-filepath ./configs/tx_size_comparison.json  --dto-version extern --no-stats --num-iter 10000000 --exclude-pfs --num-dsas 1 --results-dirname  tx_size_bf_extern_no_stats
python sweep_all_test_settable_size5.py --output-type perf --run-name tx-size-bf-extern-with_2 --cfg-filepath ./configs/tx_size_comparison.json  --dto-version extern --num-iter 10000000 --exclude-pfs --num-dsas 1 --results-dirname  tx_size_bf_extern_with_stats
python sweep_all_test_settable_size5.py --output-type micro --run-name tx-size-bf-extern-nodto_2 --cfg-filepath ./configs/tx_size_comparison.json  --dto-version no --no-stats --num-iter 10000000 --exclude-pfs --num-dsas 1 --results-dirname  tx_size_bf_extern_no_dto
python sweep_all_test_settable_size5.py --output-type micro --run-name tx-size-bf-extern-nostats_2 --cfg-filepath ./configs/tx_size_comparison.json  --dto-version extern --no-stats --num-iter 10000000 --exclude-pfs --num-dsas 1 --results-dirname  tx_size_bf_extern_no_stats
python sweep_all_test_settable_size5.py --output-type perf --run-name tx-size-bf-extern-with_3 --cfg-filepath ./configs/tx_size_comparison.json  --dto-version extern --num-iter 10000000 --exclude-pfs --num-dsas 1 --results-dirname  tx_size_bf_extern_with_stats
python sweep_all_test_settable_size5.py --output-type micro --run-name tx-size-bf-extern-nodto_3 --cfg-filepath ./configs/tx_size_comparison.json  --dto-version no --no-stats --num-iter 10000000 --exclude-pfs --num-dsas 1 --results-dirname  tx_size_bf_extern_no_dto
python sweep_all_test_settable_size5.py --output-type micro --run-name tx-size-bf-extern-nostats_3 --cfg-filepath ./configs/tx_size_comparison.json  --dto-version extern --no-stats --num-iter 10000000 --exclude-pfs --num-dsas 1 --results-dirname  tx_size_bf_extern_no_stats


#python sweep_all_test_settable_size5.py --output-type perf --run-name tx-size-turbo-extern-with_1 --cfg-filepath ./configs/tx_size_comparison.json  --dto-version extern --num-iter 10000000 --exclude-pfs --num-dsas 1 --results-dirname  tx_size_turbo_extern_with_stats
#python sweep_all_test_settable_size5.py --output-type micro --run-name tx-size-turbo-extern-nodto_1 --cfg-filepath ./configs/tx_size_comparison.json  --dto-version no --no-stats --num-iter 10000000 --exclude-pfs --num-dsas 1 --results-dirname  tx_size_turbo_extern_no_dto
#python sweep_all_test_settable_size5.py --output-type micro --run-name tx-size-turbo-extern-nostats_1 --cfg-filepath ./configs/tx_size_comparison.json  --dto-version extern --no-stats --num-iter 10000000 --exclude-pfs --num-dsas 1 --results-dirname  tx_size_turbo_extern_no_stats
#python sweep_all_test_settable_size5.py --output-type perf --run-name tx-size-turbo-extern-with_2 --cfg-filepath ./configs/tx_size_comparison.json  --dto-version extern --num-iter 10000000 --exclude-pfs --num-dsas 1 --results-dirname  tx_size_turbo_extern_with_stats
#python sweep_all_test_settable_size5.py --output-type micro --run-name tx-size-turbo-extern-nodto_2 --cfg-filepath ./configs/tx_size_comparison.json  --dto-version no --no-stats --num-iter 10000000 --exclude-pfs --num-dsas 1 --results-dirname  tx_size_turbo_extern_no_dto
#python sweep_all_test_settable_size5.py --output-type micro --run-name tx-size-turbo-extern-nostats_2 --cfg-filepath ./configs/tx_size_comparison.json  --dto-version extern --no-stats --num-iter 10000000 --exclude-pfs --num-dsas 1 --results-dirname  tx_size_turbo_extern_no_stats
#python sweep_all_test_settable_size5.py --output-type perf --run-name tx-size-turbo-extern-with_3 --cfg-filepath ./configs/tx_size_comparison.json  --dto-version extern --num-iter 10000000 --exclude-pfs --num-dsas 1 --results-dirname  tx_size_turbo_extern_with_stats
#python sweep_all_test_settable_size5.py --output-type micro --run-name tx-size-turbo-extern-nodto_3 --cfg-filepath ./configs/tx_size_comparison.json  --dto-version no --no-stats --num-iter 10000000 --exclude-pfs --num-dsas 1 --results-dirname  tx_size_turbo_extern_no_dto
#python sweep_all_test_settable_size5.py --output-type micro --run-name tx-size-turbo-extern-nostats_3 --cfg-filepath ./configs/tx_size_comparison.json  --dto-version extern --no-stats --num-iter 10000000 --exclude-pfs --num-dsas 1 --results-dirname  tx_size_turbo_extern_no_stats
